import type { Metadata } from 'next'
import './globals.css'
import NextTopLoader from 'nextjs-toploader'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: [
    { rel: 'icon', url: '/asset/favicon.ico' },
  ],
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="">
        <NextTopLoader />
        {children}
        </body>
    </html>
  )
}
